export default {
  UNPAID: 0,
  TOSHIP_PROCESS: 1,
  TOSHIP_PROCESSED: 2,
  SHIPPING: 3,
  COMPLETED: 4,
  CANCELLED_TORESPONSE: 5,
  CANCELLED_COMPLETE: 6,
  REFUND_UNPROCESSED: 7,
  REFUND_PROCESSED: 8
};
